version: '3.4'
services:
  database:
    image: postgres:alpine
    volumes:
      - .compose/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: "hana"
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD 
      PGDATA: "/var/lib/postgresql/data"
    expose:
      - 5472
    ports:
      - 5472:5472
      - 5432:5432
